# Creating matrices
* You can pass Python lists of lists to create a 2-D array (or “matrix”) to represent them in NumPy.

In [16]:
import numpy as np

data = np.array([[1, 2], [3, 4], [5, 6]])
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [17]:
#  indexing and slicing operation on matrix
data[0, 1]
data[1:3]
data[0:2, 0]

array([1, 3])

In [18]:
#  min max sum or other type of aggregate function can be used to aggerate same like as vector
data.max()
data.min()
data.sum()

np.int64(21)

In [19]:
# You can aggregate all the values in a matrix and you can aggregate them across columns or rows using the axis parameter.
data = np.array([[1, 2], [5, 3], [4, 6]])
data
data.max(axis=0)
data.max(axis=1)

array([2, 5, 6])

In [20]:
# we can add or multiply matrices using arithmetic operator 
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

# Generating random numbers

* Generator.integers, you can generate random integers from low to high but in numpy but higher number is exclusive to make it inclusive we can add `endpoint=True`

 # How to get unique items and counts
 * np.unique -- unique number can be found using this
 * You can pass the return_counts argument in np.unique() along with your array to get the frequency count of unique values
 * If you want to get the unique rows or columns, make sure to pass the axis argument. To find the unique rows, specify axis=0 and for columns, specify axis=1

In [21]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [22]:
'''To get the indices of unique values in a NumPy array (an array of first index positions of unique value
in the array), just pass the return_index argument in np.unique() as well as your array.'''

unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [23]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


# Transposing and reshaping a matrix
 * We will use arr.reshape(), arr.transpose(), arr.T  to do so.
 * If we need to switch the dimensions of a mterix or a model which expect input in different shape for that we can use `arr.rehsape()`
 *  transpose() - to reverse or change the axes of an array according to the values you specify. or we can use [ T ]
   

In [28]:
data = np.array([[1, 2],
                [5,6],
                [69,32]])
data.reshape(2, 3)
data.reshape(3, 2)

array([[ 1,  2],
       [ 5,  6],
       [69, 32]])

In [30]:
data = np.array([[1, 2],
                [5,6],
                [69,32]])
data.transpose()


array([[ 1,  5, 69],
       [ 2,  6, 32]])

In [31]:
data = np.array([[1, 2],
                [5,6],
                [69,32]])
data.T

array([[ 1,  5, 69],
       [ 2,  6, 32]])

# How to reverse an array
* np.flip() -- is used to reverse the array along an azis

In [34]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reversed_arr = np.flip(arr)

In [33]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


# Reshaping and flattening multidimensional arrays

* There are two popular ways to flatten an array: .flatten() and .ravel(). The primary difference between the two is that the new array created using ravel() is actually a reference to the parent array (i.e., a “view”). This means that any changes to the new array will affect the parent array as well. Since ravel does not create a copy, it’s memory efficient.

In [35]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [37]:
x.flatten() # convert into 1-d array
a1 = x.flatten()
a1[0] = 99
print(x)  # Original array
print(a1)  # New array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[99  2  3  4  5  6  7  8  9 10 11 12]


In [38]:
#  Using ravel 
a2 = x.ravel()
a2[0] = 98
print(x)  # Original array
print(a2)  # New array

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[98  2  3  4  5  6  7  8  9 10 11 12]
