 - What is an array ?
 An array is a structure for storing and retrieving data. We often talk about an array as if it were a grid in space, with each cell storing one element of the data.
    Arrays are homogenous 

In [3]:
#  very basic import library 
import numpy as np
 #  cration of array
a = np.array([1, 2, 3, 4, 5, 6])

#  printing the array
print(a)
#  accessing using indices 
print(a[2])
#  using slice notation same as python
print(a[:3])

[1 2 3 4 5 6]
3
[1 2 3]


In NumPy sometime a `dimension` is also called as `axis`.
For instance, the array a could represent three points, each lying within a four-dimensional space, but a has only two “axes”.
* 0-D (zero-dimensional) array referred to as a “scalar”
* 1-D (one-dimensional) array as a “vector”
* 2-D (two-dimensional) array as a “matrix”
* an N-D (N-dimensional, where “N” is typically an integer greater than 2) array as a “tensor”. 

In [5]:
#  multidimensional array 
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
# a
print(a)



array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Array attributes
* ndim --  The number of dimensions of an array is contained in the ndim attribute
* shape -- The shape of an array is a tuple of non-negative integers that specify the number of elements along each dimension.
* size --  fixed, total number of elements in array is contained in the size attribute
* dtype -- The data type is recorded in the dtype attribute.

In [11]:
print(a.ndim)
print(a.shape)
print(len(a.shape)==a.ndim)  

print(a.size)
print(a.dtype)

2
(3, 4)
True
12
int64


# Creation of basic arrays
* np.zeros() --  creating an array from a sequence of elements, you can easily create an array filled with 0’s
* np.ones() --  an array filled with 1’s
* np.empty() -- creates an array whose initial content is random and depends on the state of the memory means random values filled.
* np.arange()--  create an array with a range of elements we can also use step_size to make ap kind of thing.
* np.linspace() -- create an array with values that are spaced linearly in a specified interval or space or gap
* 

In [20]:
print(np.zeros(2))
print(np.ones(2))

print(np.empty(4))
print(np.arange(4))

print("using step",np.arange(2, 9, 2))
print(np.linspace(0, 10, num=5))

#  specifying the type of data
x = np.ones(2, dtype=np.int64)
print(x.dtype)

[0. 0.]
[1. 1.]
[ 2.5  5.   7.5 10. ]
[0 1 2 3]
using step [2 4 6 8]
[ 0.   2.5  5.   7.5 10. ]
int64


# Adding, removing, and sorting elements 
* np.sort() -- sorts the array
    argsort, which is an indirect sort along a specified axis,
    lexsort, which is an indirect stable sort on multiple keys,
    searchsorted, which will find elements in a sorted array,
    partition, which is a partial sort.
* np.concatenate() -- Concatente two array

In [23]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print(np.concatenate((a, b)))


x = np.array([[1, 2], [3, 4]])

y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)

[1 2 3 4 5 6 7 8]


array([[1, 2],
       [3, 4],
       [5, 6]])

# Can you reshape an array?
 Yes we can do it by using the  - arr.reshape()
 Using arr.reshape() will give a new shape to an array without changing the data. Just remember that when you use the reshape method, the array you want to produce needs to have the same number of elements as the original array. If you start with an array with 12 elements, you’ll need to make sure that your new array also has a total of 12 elements

In [25]:
a = np.arange(6)
print(a)
b = a.reshape(3, 2) # resaping the array
print(b)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


## How to convert a 1D array into a 2D array (how to add a new axis to an array)
 np.newaxis and np.expand_dims to increase the dimensions of your existing array
 * np.newaxis-- it will increase the dimensions of your array by one dimension when used once.
 * np.expand_dims -- You can also expand an array by inserting a new axis at a specified position with it

In [27]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)
a2 = a[np.newaxis, :]
print(a2.shape)

(6,)
(1, 6)


In [29]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)
b = np.expand_dims(a, axis=1)
print(b.shape)

(6,)
(6, 1)


# Creating Array from existing data

* We can use most basic one slicing and indexing to make an array from an existing one
* vstack -- used to stack two arrays vertically
* hstack -- used to stack arrays horizontally
* hsplit -- used to split array into various smaller group . You can specify either the number of equally shaped arrays to return or the columns after which the division should occur
* 

In [30]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
arr1 = a[3:8]
print(arr1)

[4 5 6 7 8]


In [33]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])
print(np.vstack((a1, a2)))

print(np.hstack((a1, a2)))

[[1 1]
 [2 2]
 [3 3]
 [4 4]]
[[1 1 3 3]
 [2 2 4 4]]


In [34]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [35]:
np.hsplit(x, 3) # three equal part split

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

# Basic array operations
* All the basic one like sum , subtract , divide ,modulo, product are done as same as python
* sum() - This works for 1D arrays, 2D arrays, and arrays in higher dimensions return sum of elements in an array

In [36]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [37]:
data - ones
data * data
data / data

array([1., 1.])

In [38]:
a = np.array([1, 2, 3, 4])

a.sum()

np.int64(10)

In [40]:
b = np.array([[1, 1], [2, 2]])
b.sum(axis=0)

array([3, 3])

In [41]:
b.sum(axis=1)

array([2, 4])